import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Pick Betta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" type="image/svg+xml" href="/images/logo.svg" />
      <body suppressHydrationWarning className="antialiased">
        {children}
      </body>
    </html>
  );
}
